### ISSUE TITLE
andriod9无法使用，机型红米note7。

### ISSUE THREAD

**Issue by MesopotamiazZ** [l376571926/VipVideoHelper#2]
andriod9无法使用，机型红米note7。下载到电脑上3.12M，下载到手机上3.28M。
![_20190305101649](https://user-images.githubusercontent.com/20454354/53776092-f05ab500-3f2f-11e9-8dc4-29121179c9c3.jpg)
![_20190305101654](https://user-images.githubusercontent.com/20454354/53776097-f2247880-3f2f-11e9-86b7-5c6bc209a4fa.png)
![_20190305101659](https://user-images.githubusercontent.com/20454354/53776099-f486d280-3f2f-11e9-9d59-c1497167f786.png)

**Comment by l376571926** [comment]
![image](https://user-images.githubusercontent.com/16934505/53778917-63b4f480-3f39-11e9-8475-3f68d4c2d1be.png)

bug已修复，可于应用内更新app版本，或扫描最新下载维码下载新版本
![image](https://user-images.githubusercontent.com/16934505/53779075-da51f200-3f39-11e9-8b50-843ed5a6a8a3.png)

**Comment by l376571926** [comment]
> andriod9无法使用，机型红米note7。下载到电脑上3.12M，下载到手机上3.28M。
> ![_20190305101649](https://user-images.githubusercontent.com/20454354/53776092-f05ab500-3f2f-11e9-8dc4-29121179c9c3.jpg)
> ![_20190305101654](https://user-images.githubusercontent.com/20454354/53776097-f2247880-3f2f-11e9-86b7-5c6bc209a4fa.png)
> ![_20190305101659](https://user-images.githubusercontent.com/20454354/53776099-f486d280-3f2f-11e9-9d59-c1497167f786.png)

![image](https://user-images.githubusercontent.com/16934505/53778917-63b4f480-3f39-11e9-8475-3f68d4c2d1be.png)

bug已修复，可于应用内更新app版本，或扫描最新下载维码下载新版本
![image](https://user-images.githubusercontent.com/16934505/53779075-da51f200-3f39-11e9-8b50-843ed5a6a8a3.png)

**Comment by l376571926** [comment]
> andriod9无法使用，机型红米note7。下载到电脑上3.12M，下载到手机上3.28M。
> ![_20190305101649](https://user-images.githubusercontent.com/20454354/53776092-f05ab500-3f2f-11e9-8dc4-29121179c9c3.jpg)
> ![_20190305101654](https://user-images.githubusercontent.com/20454354/53776097-f2247880-3f2f-11e9-86b7-5c6bc209a4fa.png)
> ![_20190305101659](https://user-images.githubusercontent.com/20454354/53776099-f486d280-3f2f-11e9-9d59-c1497167f786.png)

已修复bug
